"""Add chat_messages and update inbox

Revision ID: 9061da630a96
Revises: drop_linea_empleado_id
Create Date: 2026-02-21 11:11:50.361881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '9061da630a96'
down_revision: Union[str, Sequence[str], None] = 'drop_linea_empleado_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('remitente_tipo', sa.String(length=20), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('whatsapp_msg_id', sa.String(length=100), nullable=True),
    sa.Column('estado_envio', sa.String(length=20), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['inbox_id'], ['comercial.inbox.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['seg.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='comercial'
    )
    op.create_index(op.f('ix_comercial_chat_messages_id'), 'chat_messages', ['id'], unique=False, schema='comercial')
    
    op.add_column('inbox', sa.Column('modo', sa.String(length=10), server_default='BOT', nullable=False), schema='comercial')
    op.add_column('inbox', sa.Column('ultimo_mensaje_at', sa.DateTime(timezone=True), nullable=True), schema='comercial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'ultimo_mensaje_at', schema='comercial')
    op.drop_column('inbox', 'modo', schema='comercial')
    op.drop_index(op.f('ix_comercial_chat_messages_id'), table_name='chat_messages', schema='comercial')
    op.drop_table('chat_messages', schema='comercial')
    # ### end Alembic commands ###
